### ISSUE TITLE
Feature - Nuxt compatibility

### ISSUE THREAD

**Issue by bovas85** [pirony/ks-vue-fullpage#1]
Hi there, are you actively developing this? 
Is Nuxt hard to make compatible?

**Comment by pirony** [comment]
Yes i'm actively developing this pugin and will release a stable version 1.0.0 asap.
About Nuxt compatibility, I'll tell u more as soon as I integrate it

**Comment by bovas85** [comment]
I managed to get fullpage-vue plugin with nuxt by declaring it as a plugin with ssr: false flag in nuxt.config.js

Hope that helps.

**Comment by pirony** [comment]
Ok good, I'll add it to the readme, thanks @bovas85
