### ISSUE TITLE
Feature - Sections array cycling as an option

### ISSUE THREAD

**Issue by bhoggett** [pirony/ks-vue-fullpage#3]
The plugin's default behaviour is to cycle through sections when iterating
```
first -> ... -> last -> first
```
or
```
first -> last -> ... -> first
```
if iterating in reverse. 

This is fine for slideshow style presentations, but isn't typical behaviour for landing pages or an SPA.

An option to enable/disable this cycling behaviour would be welcome.  When disabled, iterations would stop at each end of the sections array.

**Comment by pirony** [comment]
loopTop and loopBottom options are yet implemented in the next version to be released ;)
