### ISSUE TITLE
Active index in default navigation remains a live link

### ISSUE THREAD

**Issue by bhoggett** [pirony/ks-vue-fullpage#4]
When using the default navigation "dots", the current page is shown as a larger dot compared to the others.  However, this remains a live navigation link as with the other dots, so clicking on it will trigger any transitions to execute again, even though the user isn't actually going anywhere new.

I suggest this is not desired behaviour and the dot representing the active page should be visual feedback only.

**Comment by pirony** [comment]
Hi @bhoggett ,
you're right, it's not an expected behaviour. It will be corrected in next version, which will be released soon.
Thanks for your feedback

**Comment by bhoggett** [comment]
Seems fixed for v1.0.2.

Nice.
