### ISSUE TITLE
Default navigation inactive on initial page render

### ISSUE THREAD

**Issue by bhoggett** [pirony/ks-vue-fullpage#5]
Odd one this:

On my dev project, the default nav dots are inactive on initial page render, but then become active after scrolling to another section, after which they work as expected.

On your jsfiddle demo, the middle dot is inactive on initial render, but the bottom one works. After first scroll, it all works as expected again.

Behaviour seems consistent on Firefox and Chrome, regardless of screen size or touch emulation.

**Comment by pirony** [comment]
Good catch!
Seems to be a z-index issue... It will be fixed in 1.0.3 ;)
Thanks again for your feedback, don't hesitate to request features and improvements if needed
