### ISSUE TITLE
Feature - option to define css 'color' property per section

### ISSUE THREAD

**Issue by bhoggett** [pirony/ks-vue-fullpage#6]
Given that there are options to set background image and colour, there needs to be an option to set the ink colour as well, for those sections where the default 'color' does not provide enough contrast to the background image/colour.

The catch is that it needs to apply to the default nav dots as well as be (optionally) available for any custom nav elements as well.

Setting the property for the section itself is easy enough through css selectors, but normally extra work would be needed to make it apply to the nav elements too.

**Comment by pirony** [comment]
I've already implemented dotNav properties: color and position... I just forgot to edit the readme with those infos ^^
You can now change dotNav properties on the fly using dotNavEnabled, dotNavPosition and dotNavColor in your options.

**Comment by pirony** [comment]
See #7
